apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: my-password
      - name: host-volume
        hostPath:
          path: /home/docker/blue-shared-volume
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: host-volume
      - image: debian
        name: debian
        volumeMounts:
        - name: host-volume
          mountPath: /host-vol
        - name: secret-volume
          mountPath: /etc/secret-data
        command: ["/bin/sh", "-c", "echo $(cat /etc/secret-data/password) > /host-vol/index.html ; sleep infinity"]
status: {}
